[lang]
language = "c++"

[compile]
# compile = false
# command = "python {FILENAME}"
compile = true
command = "clang++ -std=c++14 -stdlib=libc++ -o ../../a.out {FILENAME}"
output_dir = "../../"

[test]
testfile_dir = "../../cpg_test"