[lang]
language = "c++" # your favorite language. this is optional

[compile]
compile = true # ture if you'd prefer to compile the target file before run test
command = "go build {FILENAME}" # specify build command with {FILENAME}, which is where cpg should put filename.
output_dir = "."

[test]
testfile_dir = "./cpg_test.toml" # this is where cpg will find the test files